name: Dispatcher

on:
  workflow_dispatch: # This allows manual triggering of the dispatcher workflow

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger light-auth-core
        run: gh workflow run light-auth-core.yml@main

      - name: Trigger light-auth-astro
        run: gh workflow run light-auth-astro.yml@main

      - name: Trigger light-auth-express
        run: gh workflow run light-auth-express.yml@main

      - name: Trigger light-auth-nextjs
        run: gh workflow run light-auth-nextjs.yml@main

      - name: Trigger light-auth-nuxt
        run: gh workflow run light-auth-nuxt.yml@main

      - name: Trigger light-auth-sveltekit
        run: gh workflow run light-auth-sveltekit.yml@main
