name: Dispatcher

on:
  workflow_dispatch: # This allows manual triggering of the dispatcher workflow

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Trigger light-auth-core
        run: gh workflow run light-auth-core.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger light-auth-astro
        run: gh workflow run light-auth-astro.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger light-auth-express
        run: gh workflow run light-auth-express.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger light-auth-nextjs
        run: gh workflow run light-auth-nextjs.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger light-auth-nuxt
        run: gh workflow run light-auth-nuxt.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger light-auth-sveltekit
        run: gh workflow run light-auth-sveltekit.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
