name: Dispatcher

on:
  workflow_dispatch: # This allows manual triggering of the dispatcher workflow

jobs:
  trigger-all:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger light-auth-core
        uses: ./.github/workflows/light-auth-core.yml@main

      - name: Trigger light-auth-astro
        uses: ./.github/workflows/light-auth-astro.yml@main

      - name: Trigger light-auth-express
        uses: ./.github/workflows/light-auth-express.yml@main

      - name: Trigger light-auth-nextjs
        uses: ./.github/workflows/light-auth-nextjs.yml@main

      - name: Trigger light-auth-nuxt
        uses: ./.github/workflows/light-auth-nuxt.yml@main

      - name: Trigger light-auth-sveltekit
        uses: ./.github/workflows/light-auth-sveltekit.yml@main
