const DEFAULT_SESSION_COOKIE_NAME = "light_auth_session";
const DEFAULT_SESSION_EXPIRATION = 60 * 60 * 24 * 30; // 30 days
const ENCRYPT_SECRET_VALUE = (process.env.LIGHT_AUTH_SECRET_VALUE + "_HARD_CODED_SECRET_32_CHARS_LONG_!@#123").slice(0, 32);
const DEFAULT_BASE_PATH = "/login";

export { DEFAULT_SESSION_COOKIE_NAME, DEFAULT_SESSION_EXPIRATION,  ENCRYPT_SECRET_VALUE, DEFAULT_BASE_PATH };
