const DEFAULT_SESSION_COOKIE_NAME = "light_auth_session";
const DEFAULT_SESSION_EXPIRATION = 60 * 60 * 24 * 30; // 30 days
const INTERNAL_SECRET_VALUE = "_HARD_CODED_SECRET_32_CHARS_LONG_!@#123";
const DEFAULT_BASE_PATH = "/api/auth";

export { DEFAULT_SESSION_COOKIE_NAME, DEFAULT_SESSION_EXPIRATION, INTERNAL_SECRET_VALUE, DEFAULT_BASE_PATH };
